<?php /** @var $jsonHelper Magento\Framework\Json\Helper\Data */ ?>
<?php $jsonHelper = $this->helper(\Magento\Framework\Json\Helper\Data::class) ?>

<script type="text/x-magento-init">
    <?= $jsonHelper->jsonEncode([
        '*' => ['Ometria_AbandonedCarts/js/cart-redirect' => [
            'redirectUrl' => $block->getRedirectUrl(),
            'cookieLifeTime' => $block->getCookieLifeTime()
        ]]
    ]);
    ?>
</script>

<p><?= __('Loading Cart, please wait ...') ?></p>