<script type="text/javascript">
    setTimeout(function(){        
        var $ = jQuery;
        var storage = $.initNamespaceStorage('mage-cache-storage').localStorage;        
        storage.removeAll();
        var date = new Date(Date.now() + 24 * 1000);
        $.localStorage.set('mage-cache-timeout', date);        
        // document.location = '/checkout/cart';
    }, 1000);
</script>
<p>
Loading Cart ...
</p>