<script type="text/javascript">
    setTimeout(function(){        
        var $ = jQuery;
        var storage = $.initNamespaceStorage('mage-cache-storage').localStorage;        
        storage.removeAll();
        var date = new Date(Date.now() + 24 * 1000);
        $.localStorage.set('mage-cache-timeout', date);        
        document.location = '/checkout/cart';
    }, 1000);
</script>
<p>
Loading Cart, please wait ...
</p>
<?php //var_dump($this->getParentBlock()); ?>
<?php //var_dump($this->getParentName()); ?>
<?php //var_dump($this->getBlock('root')) ?>

<!-- 
object(Magento\Framework\View\Layout\Element)[864]
  public 0 => string 'root' (length=4)
object(Magento\Framework\View\Layout\Element)[843]
  public 0 => string 'after.body.start' (length=16)
object(Magento\Framework\View\Layout\Element)[857]
  public 0 => string 'page.wrapper' (length=12)
object(Magento\Framework\View\Layout\Element)[846]
  public 0 => string 'global.notices' (length=14)
object(Magento\Framework\View\Layout\Element)[845]
  public 0 => string 'main.content' (length=12)
object(Magento\Framework\View\Layout\Element)[850]
  public 0 => string 'columns.top' (length=11)
object(Magento\Framework\View\Layout\Element)[851]
  public 0 => string 'columns' (length=7)
object(Magento\Framework\View\Layout\Element)[849]
  public 0 => string 'main' (length=4)
object(Magento\Framework\View\Layout\Element)[846]
  public 0 => string 'page.bottom' (length=11)
object(Magento\Framework\View\Layout\Element)[850]
  public 0 => string 'before.body.end' (length=15)
object(Magento\Framework\View\Layout\Element)[865]
  public 0 => string 'root' (length=4)
object(Magento\Framework\View\Layout\Element)[846]
  public 0 => string 'after.body.start' (length=16)
object(Magento\Framework\View\Layout\Element)[861]
  public 0 => string 'page.wrapper' (length=12)
object(Magento\Framework\View\Layout\Element)[850]
  public 0 => string 'global.notices' (length=14)
object(Magento\Framework\View\Layout\Element)[857]
  public 0 => string 'main.content' (length=12)
object(Magento\Framework\View\Layout\Element)[853]
  public 0 => string 'columns.top' (length=11)
object(Magento\Framework\View\Layout\Element)[845]
  public 0 => string 'columns' (length=7)
object(Magento\Framework\View\Layout\Element)[849]
  public 0 => string 'main' (length=4)
object(Magento\Framework\View\Layout\Element)[850]
  public 0 => string 'page.bottom' (length=11)
object(Magento\Framework\View\Layout\Element)[853]
  public 0 => string 'before.body.end' (length=15)
object(Magento\Framework\View\Layout\Element)[846]
  public 0 => string 'page.wrapper' (length=12)
 -->