<?php
/** @var Ometria\Core\Block\Adminhtml\System\Config\Logs\DownloadButton $block */
?>

<button class="scalable" type="button" id="ometria_logs_download">
    <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
</button>

<script>
    require([
        'jquery'
    ], function ($) {
        $(function () {
            $('#ometria_logs_download').on('click', function () {
                window.location = "<?= $block->escapeJs($block->escapeUrl($block->getDownloadUrl())) ?>"
            });
        });
    });
</script>
